### ISSUE TITLE
checkin typings to git?

### ISSUE THREAD

**Issue by hrj** [jvilk/BrowserFS#130]
Similar to https://github.com/plasma-umass/doppio/issues/406, shall I make a PR to checkin the `typings` folder?

Also, why are `dist/` files checked in to the repo?

**Comment by jvilk** [comment]
I checked `dist

**Comment by jvilk** [comment]
I checked `dist` into the repo for Bower. Do people still use Bower? Maybe not?

**Comment by jvilk** [comment]
And yeah, if you have time, you should check the typings in. :)
