### ISSUE TITLE
Tests fail on Ubuntu, Firefox & Chromium

### ISSUE THREAD

**Issue by jvilk** [jvilk/BrowserFS#132]
Reproduced in an Ubuntu virtual machine. `std-streams.js` fails.

Investigating.

**Comment by jvilk** [comment]
`std-streams.js` fails the second time it is run with an alternative `Buffer` implementation: one that uses a standard array internally. When we push data onto the stream, it doesn't propagate to the callback we register.

I have no idea why this is an OS-specific bug. It does not occur on my Mac.

**Comment by jvilk** [comment]
Fixed in this commit:

https://github.com/jvilk/BrowserFS/commit/7f1b253db7ec3e7556ca04e7cc61977769b3d1f4

**Comment by hrj** [comment]
Confirming that this works for me.

However, Firefox now consistently hangs with `test #321`, although that might be a problem with `karma` or something specific to my setup. I notice a similar hang when running doppio tests with the same setup.
