### ISSUE TITLE
There are no typings for BrowserFS on DefinitelyTyped.

### ISSUE THREAD

**Issue by zebMcCorkle** [jvilk/BrowserFS#136]
I see BrowserFS is written in TypeScript, so it shouldn't be too hard to get typings published to DefinitelyTyped. I'm writing a TypeScript app and it would be very beneficial to have autocomplete support in Atom.

**Comment by jvilk** [comment]
The NPM module has typings included, so it should work out of the box. are you having trouble using it?

**Comment by zebMcCorkle** [comment]
I'm on the browser, I guess I could use browserify.

**Comment by jvilk** [comment]
Yeah, browserify or webpack. There's no good way to generate web-friendly typings when you use commonjs internally. If you know of a way, let me know.
