### ISSUE TITLE
Replace usage of document.write to inject polyfill

### ISSUE THREAD

**Issue by cmercur2** [jvilk/BrowserFS#142]
Currently this unusable an asynchronous module in any browser besides Chrome due to the injection of IEBinaryToArray_ByteStr in all browsers that are not Chrome.

**Comment by jvilk** [comment]
This shouldn't be an issue; we release BrowserFS as a single UMD module. It should work in RequireJS, Browserify, Webpack, or in a script tag that exposes the `BrowserFS` global.

**Comment by jvilk** [comment]
Oh, I see the issue now. We use `document.write`. But I think that code only gets injected if it's IE?

I will accept a PR that fixes this issue. Perhaps we can inject the script another way, using other DOM methods.
