### ISSUE TITLE
WorkerFS initialization fails in Chrome

### ISSUE THREAD

**Issue by mycql** [jvilk/BrowserFS#143]
The docs state that to use WorkerFS, BrowserFS has to be initialized in the Web Worker

```BrowserFS.initialize(new BrowserFS.FileSystem.WorkerFS(self));```

but initialization fails because of Worker support checking, since 'Worker' is not defined under a Worker context in Chrome
###### WorkerFs.ts
```
public static isAvailable(): boolean {
    return typeof Worker !== 'undefined';
  }
```

**Comment by jvilk** [comment]
Oh! Good point. That check will need to be changed to check if the current context can create workers OR if it is currently running inside of a worker.

**Comment by jvilk** [comment]
This looks like an appropriate check: http://stackoverflow.com/a/11979803

@mycql would you be willing to make a PR with the change?

**Comment by jvilk** [comment]
Fixed.
