### ISSUE TITLE
Switch to Dropbox V2 API

### ISSUE THREAD

**Issue by jvilk** [jvilk/BrowserFS#144]
We are using Dropbox-js, which uses the Dropbox V1 API. This API is deprecated and may be removed soon. We should switch to Dropbox V2 at some point, which does not have a JavaScript SDK, but has well-documented REST endpoints.

**Comment by jvilk** [comment]
June 28, 2017 is when Dropbox turns off API v1.

**Comment by jvilk** [comment]
There's a new JavaScript SDK out, too:

https://www.npmjs.com/package/dropbox

**Comment by fr500** [comment]
+1

**Comment by jvilk** [comment]
Dropbox is [working to accept my TypeScript PR for the JS SDK](https://github.com/dropbox/dropbox-sdk-js/pull/96), which adds TypeScript type annotations to the SDK. This will make it much easier to write code against the SDK, which returns rather complex JSON objects.

**Comment by bpowers** [comment]
v2.5 of the API is out, which I think includes your TypeScript typings: https://github.com/dropbox/dropbox-sdk-js/releases/tag/v2.5.0 (but hard to tell with their crappy release notes)

**Comment by jvilk** [comment]
Yeah, it should have the typings. The limiting factor at the present moment is my free time.

**Comment by jvilk** [comment]
V1 will stop working in September now; they extended the deadline.

https://blogs.dropbox.com/developers/2017/06/updated-api-v1-deprecation-timeline/

**Comment by jvilk** [comment]
[I have Dropbox V2 working in a branch.](https://github.com/jvilk/BrowserFS/tree/dropbox_v2)

**Comment by jvilk** [comment]
The `master` branch now has Dropbox V2 support, and it will be included in the first v2.0 release.
