### ISSUE TITLE
Documentation for running inside Node.js

### ISSUE THREAD

**Issue by dselman** [jvilk/BrowserFS#166]
I'm struggling to get BrowserFS to work from a Node.js application.

I've npm installed.

In my Node.js file I then require:

`const BrowserFS = require('../node_modules/browserfs/dist/node');
`
Note that this is not the same as documented on the README.MD -- which seems to be missing?

When I run I get this:
```

TypeError: cb is not a function
      at node_modules/browserfs/dist/node/core/file_system.js:281:24
      at InMemoryFileSystem.SynchronousFileSystem.open (node_modules/browserfs/dist/node/core/file_system.js:474:13)
      at InMemoryFileSystem.BaseFileSystem.readFile (node_modules/browserfs/dist/node/core/file_system.js:279:14)
```

My code:

```
    loadConnectionProfile(connectionProfile) {
        const self = this;
        const result = new Promise(
          function(resolve,reject) {
              self.fileSystem.readFile(PROFILE_ROOT + connectionProfile + '/' + CONNECTION_FILE, ENCODING,
              (err, contents) => {
                  if(!err) {
                      resolve(JSON.parse(contents));
                  }
                  else {
                      reject(err);
                  }
              });
          });

        return result;
    }

```

**Comment by jvilk** [comment]
I agree that the Node.js use case could be better documented. I updated the `README`; `main` is now `index`.

What is `self.fileSystem`? If this is a raw FileSystem object, then your code will not work. You should only access file systems via BrowserFS's emulated `fs` module, which standardizes the arguments to the underlying FileSystem object:

```javascript
var BrowserFS = require('browserfs/dist/node/index');
var bfs_fs = BrowserFS.BFSRequire('fs');
// Note: If you use Node's path module to manipulate paths passed to BrowserFS, your code will not
// work on Windows. (BrowserFS only supports Unix-style paths.)
var bfs_path = BrowserFS.BFSRequire('path');
var myFilesystem = new BrowserFS.FileSystem.InMemory();
bfs_fs.initialize(myFilesystem);

fs.readFile(PROFILE_ROOT + connectionProfile + '/' + CONNECTION_FILE, ENCODING,
  (err, contents) => {
  // etc
});
```

Make sense?

If you need multiple filesystems in the same file system hierarchy, then you can use a `MountableFileSystem` and `mount` them at different directories in the filesystem.

**Comment by dselman** [comment]
Thank you, that helps!

**Comment by jvilk** [comment]
@dselman should I close this issue and consider it solved, or did you have further difficulties / requests?

**Comment by dselman** [comment]
I have verified that my Node.js code now works with an InMemory FS. Thank you very much for your prompt reply and help - I will close this.

**Comment by jvilk** [comment]
No problem. :) May I ask what you are using it for? I figured the main use case for the Node interface is that it's easy to read zip files -- which is what my Doppio project uses it for. That's why the documentation is rather sparse.

**Comment by dselman** [comment]
I have some code that stores configuration information using the file system. That code needs to run both in a Node.js environment and in the browser.
