### ISSUE TITLE
Expose `supportProps` as configurable for KeyValueFileSystems

### ISSUE THREAD

**Issue by Swivelgames** [jvilk/BrowserFS#167]
I've begun implementing BrowserFS for a large project I'm working on, but the application that's utilizing this needs to have the ability to modify file properties (things like chmod, et cetera). I'm utilizing the `IndexedDB` backend for the project.

While perusing the source code, I noticed `key_value_filesystem.ts` defines `SyncKeyValueFileSystemOptions` with the following block of comments:

```javascript
  /**
   * Should the file system support properties (mtime/atime/ctime/chmod/etc)?
   * Enabling this slightly increases the storage space per file, and adds
   * atime updates every time a file is accessed, mtime updates every time
   * a file is modified, and permission checks on every operation.
   *
   * Defaults to *false*.
   */
  // supportProps?: boolean;
  /**
   * Should the file system support links?
   */
  // supportLinks?: boolean;
```

The argument in the comment makes perfect sense, but I think it's a case-by-case basis depending on how BrowserFS is being implemented within a particular application. Is it possible to complete development for and expose these two options as configurable options to implementers? In my case, both `links` and `props` are features I require for the application I'm working on, and the trade-off of increased operation time may be acceptable given my scenario.

As I'm not very familiar with the code-base, I can't promise I can contribute too much, but I'd love to lend my assistance if possible.

**Comment by Swivelgames** [comment]
Still familiarizing myself with this project, but I'm beginning to understand (at least partially) how the data is structured in the `ArrayBuffer` within the `IndexedDB` store.

After additional perusing, and some fiddling in the console, I found this was generally a good way to retrieve some of the `inode` information about a `folder`, but not necessarily a file.

Based on the constructor in `[inode.ts](https://github.com/jvilk/BrowserFS/blob/master/src/generic/inode.ts#L23-L28)`, I came up with this just for testing (disclaimer: it's a bit nasty):

```
var arrBuff;

db
    .transaction(['browserfs'], 'readwrite')
    .objectStore('browserfs')
    .get('95050189-9603-4724-8382-e15ad70bc20c')
    .onsuccess =
        (event) => {
            arrBuff = event.target.result;

            console.log(
                /* id    */ new TextDecoder('utf-8').decode(new Uint8Array(arrBuff.slice(30))),
                /* size  */ (new Uint32Array(arrBuff.slice(0,4))),
                /* mode  */ (new Uint16Array(arrBuff.slice(4,6))),
                /* atime */ (new Float64Array(arrBuff.slice(6,14))),
                /* mtime */ (new Float64Array(arrBuff.slice(14,22))),
                /* ctime */ (new Float64Array(arrBuff.slice(22,30)))
            );
        };
```

Of course, that being said, `atime`, `mtime`, and `ctime` are in milliseconds, not seconds.

At the moment I've created a bit of a wrapper for my file system that I'm preparing to use to implement `chmod` and `chown`, while proxying all other methods. It's a bit of a monkey-patch solution, though. I'm thinking I'll need to figure out how each of the ID's correlate with objects in the database. My assumption is that there are entries for inodes, and entries for file objects (i.e., the inode entry contains the ID of the corresponding file/directory entry). Not exactly how these correlate with actual path names just yet, but I'm still digging around in there. Once I have this mapped out I might be able to contribute something like this back to the project, maybe even as a `IndexedDBWithInodes` backend or something.

**Comment by Swivelgames** [comment]
I'm beginning to understand how the KeyValueStore works. Essentially the root inode is stored with the "/" key, and it all stems from there. It's ID points to its folder structure (a stringified JSON object containing the `'resource name': 'inode id'`, and each inode entry contains the id of that resource's contents (be it more resources if its a directory, or a file's contents).

A snippet of some of the data I discovered:
```javascript
{
	"ef960a5d-34b9-41b9-b1d3-8c440497267b": "{\"motd\":\"b33926f7-7715-4b59-b750-2785a7c7249c\"}",
	"b743e471-1a15-4891-b7b1-762e10e14b3a": "FILE CONTENTS IN ASCII",
	"b33926f7-7715-4b59-b750-2785a7c7249c": {
		atime: 1480486312991,
		ctime: 1480486312991,
		id: "b743e471-1a15-4891-b7b1-762e10e14b3a",
		mode: 33188,
		mtime: 1480486312997,
		size: 91
	}
}
```

**Comment by Swivelgames** [comment]
@jvilk Totally understandable! This time of year is hectic for everyone :)

As for `supportProps`, would you also accept a pull request that implements `utimes` _and_ `chown / chmod`? The latter is what my personal use case needs mostly. Since `fs.chown` takes `uid <Integer>` and `gid <Integer>`, and `fs.chmod` is just octal masking and arithmetic, the implementation should be straightforward enough.

As for `utimes`, ensuring that `atime` and `mtime` get updated based on `reads`/`writes` (respectively) is something I'll also need to keep in mind.

I'd love to put in some work on this. I'll need to familiarize myself with the codebase a bit more. I may have a pull request for you in the future, but we'll see if I have the ability to.

Thanks a lot!

**Comment by jvilk** [comment]
> As for supportProps, would you also accept a pull request that implements utimes and chown / chmod? 

Yup, but you need to make it opt-in. If you add `chown`/`chmod`, you're going to change what information is stored in each file system node. Otherwise, if you upgrade from an older version of BFS to BFS + `chown`/`chmod` support, suddenly your old file system no longer works because it doesn't have this new information.

Unless you think that a graceful upgrade is possible... in which case, you'd need to demonstrate that with a solid unit test.

> As for utimes, ensuring that atime and mtime get updated based on reads/writes (respectively) is something I'll also need to keep in mind.

This shouldn't be too bad; they all use the same base file class. You'll want to write a unit test that tests this thoroughly, though (I'll expect tests with a PR). :)

Would you also need to change `process.getgid()`/`process.getuid()`?

> I'd love to put in some work on this. I'll need to familiarize myself with the codebase a bit more. I may have a pull request for you in the future, but we'll see if I have the ability to.

I have faith! If you get stuck, feel free to open an in-progress PR and ask questions.

**Comment by Swivelgames** [comment]
> Yup, but you need to make it opt-in. If you add chown/chmod, you're going to change what information is stored in each file system node.

That's true for `chown`, but not for `chmod`. `chmod` simply changes the `mode` on the inode; I will certainly supply some tests for this to show it will remain compatible. I can certainly make both of them optional, though, if necessary. `chown` will certainly require the addition of `gid` and `uid` properties on the inode, which increases the footprint of the data among other things.

> I'll expect tests with a PR

Definitely, definitely, definitely.

> Would you also need to change `process.getgid()`/`process.getuid()`?

I'm not sure about that. Because `fs.chown` simply modifies properties on the inode of a filesystem resource. Especially in an emulated filesystem that doesn't implement a consistent auth implementation, the true owner or group is essentially irrelevant to BrowserFS. Would we need to utilize `process.getgid()` or `process.getuid()` in any way for this? Unless I'm getting confused (which is quite possible 😆 ).

Emscripten seems to take a similar approach:

```
"The underlying implementation does not support user or group permissions. The caller is always treated as the owner of the folder."
```

In a sense, we simply set the `gid` or `uid` to whatever the developer wishes, and assume it's correct based on their implementation?

> Unless you think that a graceful upgrade is possible... in which case, you'd need to demonstrate that with a solid unit test.

It should be simple enough, I assume, to essentially default the `gid` or `uid` to `0` (i.e., root) if none is present on an existing `inode` object? Or would that not be an intended result? In the end, existing systems that do not currently utilize these properties shouldn't be restricted by the addition of these inode properties since they're not being utilized.

**Comment by Swivelgames** [comment]
@jvilk Before beginning work on this, I wanted to chime in and let you know that I was hoping to pull this down and begin working on implementing something like this. I know it's been awhile since we've spoken about this.

**Comment by jvilk** [comment]
Thanks for letting me know. Go ahead and have at it!

**Comment by Swivelgames** [comment]
@dr-vortex Awesome to hear! The project I was working ended up taking an extended backseat and I only got about half way through the implementation of this before other things took priority over the project. Really glad to see this got implemented! I may go back and revisit this project because of this.

**Comment by dr-vortex** [comment]
@Swivelgames Thanks for the support!
