### ISSUE TITLE
Relative directories are missing when a FS is mounted in an EmscriptenFS

### ISSUE THREAD

**Issue by raptor** [jvilk/BrowserFS#170]
I am running DOSBox in a browser via Emscripten with BrowserFS mounted filesystems.  I found that relative directories operations fail within the BrowserFS filesystems.

Copying a file in the raw EmscriptenFS via relative path works.  See below:

![image](https://cloud.githubusercontent.com/assets/6452412/21593859/35999a04-d0d9-11e6-82c0-25b8cb0a15e2.png)

But copying a file in a BrowserFS filesystem via relative path fails:

![image](https://cloud.githubusercontent.com/assets/6452412/21593887/68ca85d2-d0d9-11e6-9241-f5046ac4029e.png)

You'll notice the `..` and `.` directories are missing in the BrowserFS filesystems but not in the Emscripten ones.

In my setup I have a MountedFileSystem() set up in the EmscriptenFS as `/emulator` with an AsyncMirror(IndexedDB) under `/emulator/starsdat`

This seems to happen however I have the filesystems set-up within BrowserFS.  The game I'm attempting to run (Stars!) uses the relative directories in file operations and so I cannot use BrowserFS to persist data with it.

**Comment by jvilk** [comment]
I'm guessing there's a bug in the Emscripten plugin. Like Node's FS interface, BFS doesn't list `.` and `..` as items in the current directory. Perhaps I have to explicitly add them in the Emscripten FS plugin.

**Comment by jvilk** [comment]
@raptor can you try 1.2.0 and let me know if it's fixed? If it's not, reopen this bug.

Thanks.

**Comment by raptor** [comment]
This appears to be fixed.  THANKS!

**Comment by jvilk** [comment]
No problem! Let me know if you have other problems.
