### ISSUE TITLE
Websocket Support

### ISSUE THREAD

**Issue by svenefftinge** [jvilk/BrowserFS#173]
We are looking for a solution that allows for using fs from a browser, connecting to a remote node server's fs. Is that already possible with BrowserFS or do we need another backend?

From what I understood the webworker implementation comes close.

**Comment by jvilk** [comment]
To answer your other question, BrowserFS provides read-only access to a file system over HTTP GETs, but assumes that the files are static (e.g., the files on the server do not change) and requires you to generate an index of those files.

**Comment by jvilk** [comment]
Oh, and if the second bullet is what you want, you'd need to write a new backend for that purpose. It should be relatively straightforward if you have poked at TypeScript code before, and there are existing tests you can run your file system against (just make a factory!). :)

**Comment by svenefftinge** [comment]
Thanks, for the answer. Yes, of course there are security concerns but it can be solved in different ways and doesn't necessarily need to be a responsibility of the BrowserFS backend. 
In my context, we spawn individual docker images in  a private cloud. Those servers don't run long and are only accessible through a proxy.
But I understood that you don't see this in the core framework, which is ok of course. I just wanted to make I don't miss something.
