### ISSUE TITLE
HTML5 file storage missing flags.pathNotExistsAction on writeFile

### ISSUE THREAD

**Issue by ZeeCoder** [jvilk/BrowserFS#178]
I tried to make use of the filesystem api, but I think I'm doing something wrong.
I used Webpack, here is a screenshot of the code and result:

![writetest](https://cloud.githubusercontent.com/assets/3679506/26676748/fd9ad3ee-46c0-11e7-86cc-4177fcbc273f.png)
![html5error](https://cloud.githubusercontent.com/assets/3679506/26676755/03181ebc-46c1-11e7-99d7-5ab60a76ddfb.png)

I tried with and without the `install(window)` call, and also without the 'w+' flag.
I'm not sure how to access the FileFlag class, which this method seems to be requiring?

**Comment by jvilk** [comment]
Hey @ZeeCoder.

You should instead interact with the Node FS module, not the file system class directly:

```
const html5fs = new browserfs.FileSystem.HTML5(100);
html5fs.allocate(() => {
  browserfs.initialize(html5fs);
  browserfs.install(window);
  const fs = browserfs.BFSRequire('fs');
  // use fs like the node fs module.
});
```

Think of BrowserFS as a Unix-like file system. You need to tell it what to use as root (`/`). On Linux, you'd say "mount this EXT4 partition as root". Here, you're saying "mount the HTML5 FileSystem as root". Once that's done, you interact with the resulting file system through a single global API.

I hope that helps! I realize this is a weird way of doing things in JavaScript. Let me know if you have other issues.
