### ISSUE TITLE
Tests failed on Safari Browser

### ISSUE THREAD

**Issue by nidhimundra** [jvilk/BrowserFS#179]
On running tests, all the tests pass on Chrome and Firefox, but they fail on Safari. Pasting the error below:
`Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 704 of 704 SUCCESS (26.366 secs / 22.716 secs)
Firefox 53.0.0 (Mac OS X 10.12.0): Executed 667 of 667 SUCCESS (23.917 secs / 22.596 secs)
Safari 10.1.0 (Mac OS X 10.12.4) ERROR
  TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
  at test/harness/test.js:20219
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 704 of 704 SUCCESS (26.366 secs / 22.716 secs)
Firefox 53.0.0 (Mac OS X 10.12.0): Executed 667 of 667 SUCCESS (23.917 secs / 22.596 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browserfs@1.3.0 test:karma: `karma start karma.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browserfs@1.3.0 test:karma script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nidhi/.npm/_logs/2017-06-02T21_29_25_594Z-debug.log
ERROR: "test:karma" exited with 1.`

**Comment by jvilk** [comment]
I opened a bug [on the buffer package](https://github.com/feross/buffer/issues/166), which causes this error.

I don't have a good workaround right now.

**Comment by jvilk** [comment]
Note that this is only a problem in our test environment. Users may encounter this when using the `buffer` package or BrowserFS within an iframe in Safari.
