### ISSUE TITLE
Using Dropbox FS in Browsix Latex Editor makes large number of API calls 

### ISSUE THREAD

**Issue by nidhimundra** [jvilk/BrowserFS#180]
Using Dropbox FS in Browsix latex editor tries to fetch all the latex files from Dropbox, and subsequently, generates a large number of API calls. The average network time of these comes around ~100ms, but some are really quick (~7 ms) and, some are too slow (~500 ms). 
Is there any way to avoid it from fetching these files from Dropbox? 

![screen shot 2017-06-14 at 4 31 54 pm](https://user-images.githubusercontent.com/4862546/27191583-3651b74c-51c6-11e7-82e7-50a58634968a.png)

**Comment by jvilk** [comment]
Not that I know of. If LaTeX reads the file `foo.tex`, then the Dropbox FS will read `foo.tex` from Dropbox.

There's some basic caching in the Dropbox FS, but it still needs to check in with the Dropbox server to see if the file has changed.

**Comment by nidhimundra** [comment]
Yes, I am storing the .tex files and .bib files on Dropbox, but from where is it fetching other files of pdflatex? Is it trying to fetch those as well from Dropbox?

**Comment by jvilk** [comment]
That depends on your configuration of BrowserFS. Without seeing the code, I can't answer that question. Is your code available somewhere?

**Comment by nidhimundra** [comment]
You can find my code at https://github.com/nidhimundra/browsix/blob/dropbox-fs-support/examples/latex-editor/app/scripts/main.js#L8 and https://github.com/nidhimundra/browsix/blob/dropbox-fs-support/src/kernel/kernel.ts#L2537

**Comment by jvilk** [comment]
DropboxFS is working as intended.
