### ISSUE TITLE
Tests fail in a fresh Travis (Ubuntu Trusty) environment

### ISSUE THREAD

**Issue by wmhilton** [jvilk/BrowserFS#186]
I hate to be the bearer of bad news. But on my fork, Travis is using its newer Ubuntu version by default, and the tests consistently fail at test 484 of 667. Probably the main difference and culprit is running Firefox 50 instead of Firefox 30. Which on the down side suggests that the tests may be broken on modern Firefox on modern Ubuntu.

Example:
https://travis-ci.org/wmhilton-contrib/BrowserFS/builds/259587627

**Comment by jvilk** [comment]
I'll have to see which test that is, and why it is failing. Thanks for the report.

**Comment by wmhilton** [comment]
I am not sure how to determine what test 484 is.

**Comment by wmhilton** [comment]
Oooh! On the bright side, the tests fail on my Windows computer because of `TypeError: Cannot read property 'pipesCount' of undefined` which is quite popular on Google right now with Node v8.

**Comment by jvilk** [comment]
Is this still a problem, @wmhilton?

**Comment by jvilk** [comment]
I changed our unit tests to run in Travis Trusty, and everything appears to work.
