### ISSUE TITLE
Test breakage in Node 8.0 and 8.1

### ISSUE THREAD

**Issue by wmhilton** [jvilk/BrowserFS#187]
`TypeError: Cannot read property 'pipesCount' of undefined`

> @jvilk: Why isn't npm test running? It should run on all major operating systems (Mac/Linux/Windows). That should be filed as a bug!

I got it working! A quick googling suggests it's related to [archiver](https://github.com/archiverjs/node-archiver/issues/236). The bug is unique to Node 8.0 and 8.1 apparently. I can confirm after upgrading to node 8.2 the tests execute flawlessly.

So I think that's resolved.

**Comment by jvilk** [comment]
Thanks for investigating. I'll close as fixed, since it's a bug in a dependency.
