### ISSUE TITLE
`Cannot load browser "Chrome Canary": it is not registered!`

### ISSUE THREAD

**Issue by wmhilton** [jvilk/BrowserFS#188]
It's awesome that the tests want to test every browser on my computer, but I've got so many browsers you can't handle it! 😛 

```
INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
INFO [launcher]: Launching browsers Chrome, Chrome Canary, Firefox, Firefox Nightly, IE with concurrency 1
ERROR [launcher]: Cannot load browser "Chrome Canary": it is not registered! Perhaps you are missing some plugin?
ERROR [launcher]: Cannot load browser "Firefox Nightly": it is not registered! Perhaps you are missing some plugin?
ERROR [karma]: Found 2 load errors
```

Meanwhile I'm getting around it by setting `TRAVIS=true npm test` which makes it only test Firefox.

**Comment by wmhilton** [comment]
FYI I have zero experience with karma so if that's a newb error that's why.

**Comment by jvilk** [comment]
It doesn't seem common to autodetect browsers, but I added it in to simplify my life and avoid hardcoding values for different setups.

I'm also using an older version of the `detect-browsers` package, since the newer version goes full ES6 modules. It's possible this is fixed in a newer version.

**Comment by wmhilton** [comment]
> It's possible this is fixed in a newer version.

I considered that... and then I thought... what the heck, what could go wrong with stripping spaces?

**Comment by wmhilton** [comment]
That's a pretty sweet test setup by the way. I like that it autodetects browsers.
