### ISSUE TITLE
Promises API

### ISSUE THREAD

**Issue by juancampa** [jvilk/BrowserFS#230]
There's a new (albeit experimental) promise API. I just wanted to create an issue and discuss if it's worth implementing in BrowserFS. Any thoughts?

[https://nodejs.org/api/fs.html#fs_fs_promises_api](https://nodejs.org/api/fs.html#fs_fs_promises_api)

Thanks for this great module btw.

**Comment by jvilk** [comment]
Interesting. I think I'd wait for it to become more stable; it would be a lot of churn to keep up with an experimental API.

**Comment by errorx666** [comment]
Would you consider accepting a PR for this functionality?  I think I could just shim most of the existing functions.

**Comment by dbrock** [comment]
Maybe time for this now? :)

**Comment by RiccardoBiosas** [comment]
it'd definitely be super useful, currently I have to promisify each of the node `fs` methods

**Comment by dr-vortex** [comment]
In case your interested @RiccardoBiosas @sixman9 @juancampa @dbrock:

Added in c8b960b
