### ISSUE TITLE
Support fs.open on directories

### ISSUE THREAD

**Issue by mxrth** [jvilk/BrowserFS#244]
On node on linux `fs.openSync('/tmp', 'r')` works fine, whereas BrowserFS only allows open on files. This would, among other things, allow fstatting on directories.
(My concrete use case is to use BrowserFS to run go binaries in the browser via the upcoming wasm-backend. The go standard lib does an `open`, `fstat`, `readdir` sequence whenever it gets an directory listing)

**Comment by wapacz** [comment]
I'm trying to use BrowserFS with wasm (golang based, using 1.16 version) and facing this issue when trying to list files with Golang. It tries to open directory to list files. I was trying to apply misak113 changes but without success, facing another error. Are there any plans regarding this?
