### ISSUE TITLE
Cannot depend on this package with NPM / Yarn in a TypeScript package.

### ISSUE THREAD

**Issue by ElvishJerricco** [jvilk/BrowserFS#247]
After running `npm install browserfs`, I can use it from JS, but `tsc` gives many errors like this:

```
node_modules/browserfs/dist/node/generic/preload_file.d.ts:190:82 - error TS2304: Cannot find name 'Buffer'.

190     constructor(_fs: T, _path: string, _flag: FileFlag, _stat: Stats, contents?: Buffer);
```

Ok, fine, I can install some `@types` dependencies, though I would have hoped that would have been done for me. If I add these to my `package.json`:

```json
{
  ...
  "devDependencies": {
    "typescript": "^2.9.2",
    "@types/archiver": "^2.0.0",
    "@types/async": "2.0.31",
    "@types/body-parser": "^1.16.4",
    "@types/express": "^4.0.36",
    "@types/filesystem": "0.0.28",
    "@types/isomorphic-fetch": "^0.0.34",
    "@types/mocha": "^2.2.41",
    "@types/node": "~7.0",
    "@types/rimraf": "~0.0.28",
    "dropbox": "2.5.7"
  },
  "dependencies": {
    "browserfs": "^1.4.3"
  }
}
```

I get a bunch of errors like:

```
node_modules/browserfs/dist/node/backend/Dropbox.d.ts:93:18 - error TS2503: Cannot find namespace 'Dropbox'.

93     convert(err: Dropbox.ApiError, path?: string | null): ApiError;
```

Manually adding every dev dependency of browserfs to my dev dependencies didn't help either.

**Comment by ElvishJerricco** [comment]
Derp. I was missing `@types/dropboxjs`.

**Comment by jvilk** [comment]
I think the "right way" to do this is to explicitly depend on `@types` packages, but I hesitated to do that because so many people use BrowserFS without TypeScript. I'd have to see if the ecosystem has changed at all.
