### ISSUE TITLE
fs.lstat returns size: -1

### ISSUE THREAD

**Issue by wmhilton** [jvilk/BrowserFS#249]
Can you think of an edge case where stat might return -1 for size? It appears to be happening when I write to a file in an `OverlayFS<HTTPRequestFS, InMemoryFS>` setup.

This is with version 2.0.0

**Comment by wmhilton** [comment]
Figured it out. It happens if the HTTP server does not send Content-Length headers. I'm not sure how to address this.

I'm experiencing this in the Karma dev server. It will respond with Content-Length headers if the request is a Range request (such as those made when seeking in a media player) but not for ordinary requests.

I was going to open a PR in karma but they just released a new major version that my code's not compatible with, and I don't know if they'd accept a PR to the old 2.x branch.

I wonder if other servers are like this, and whether it makes sense to use a range request header in HttpRequestFS to work around this.

**Comment by jvilk** [comment]
Content-Length is present on almost every HTTP request. I think if it's not present, the HTTPDownloadFS should revert to a synchronous XHR to figure out the true size of the resource. (Unless there's some other second way that avoids the synchronous download.)

**Comment by wmhilton** [comment]
Yes, I think the thing to do here is consider it a bug in `karma`. I'll get `karma`'s http server to add content-length headers.

But I'm going to wait until karma 3.x is a little more battle-tested. Then port my code over to it. Then put in the PR.
