### ISSUE TITLE
IsoFS may hang in initialization

### ISSUE THREAD

**Issue by 1koval** [jvilk/BrowserFS#250]
https://github.com/jvilk/BrowserFS/blob/28a26cbcb89b5cef59a586f55045aabe98561f47/src/backend/IsoFS.ts#L1200

It seems like an endless busy loop in IsoFS initialization.
Boundary check might be missing and it creates endless loop 
with index growing above data size (`i > data.byteLength`).

To reproduce:
```
var BrowserFS = require("browserfs");
var Buffer = BrowserFS.BFSRequire('buffer').Buffer;

var mountConfig = {
    fs: "MountableFileSystem",
    options: {
        "/iso": {
            fs: "IsoFS",
            options: {
                data: Buffer.from(''),
                name: 'name'
            }
        }
    }
};
BrowserFS.configure(mountConfig, function (e) {
    console.log('never');
});
console.log('never');
```

Potential fix:
`- while (!vdTerminatorFound)`
 `+ while ((!vdTerminatorFound) && (i < data.byteLength))`

**Comment by dr-vortex** [comment]
Closing (stale). If you would like to reopen this issue, please do so by creating a new issue in the relevant repositories of @browser-fs
