### ISSUE TITLE
IE11: SCRIPT5045: Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by ZaDarkSide** [jvilk/BrowserFS#261]
In file [`browserfs.js`](https://github.com/jvilk/BrowserFS/releases/download/v1.4.3/browserfs.js) line `16800`

```js
	Buffer.prototype.slice = function slice (start, end) {
	  var len = this.length
	  start = ~~start
	  end = end === undefined ? len : ~~end
```

I get error *SCRIPT5045: Assignment to read-only properties is not allowed in strict mode.*

**Comment by jvilk** [comment]
This is a bug in the [buffer module](https://www.npmjs.com/package/buffer):

https://github.com/feross/buffer/issues/224
