### ISSUE TITLE
TypeError: PATH.join2 is not defined

### ISSUE THREAD

**Issue by notiv-nt** [jvilk/BrowserFS#270]
![image](https://user-images.githubusercontent.com/10743009/55087925-e7d34580-50bb-11e9-83d6-8f56881bc6fc.png)

I thought to replace everywhere with just `join`, but the tests don't work on my computer, I can't check

![image](https://user-images.githubusercontent.com/10743009/55087907-e144ce00-50bb-11e9-8eb6-2a5d834b6c02.png)

**Comment by notiv-nt** [comment]
https://github.com/notiv-nt/BrowserFS/commit/e4bcd55a0103c38cec15a35273bd1636a2037241
Works for me

**Comment by jvilk** [comment]
@notiv-nt Interesting; I wonder if Emscripten changed their internal API. Could you open a PR so I can review and potentially merge?

**Comment by notiv-nt** [comment]
@jvilk ?

**Comment by dr-vortex** [comment]
Closing (stale). If you would like to reopen this issue, please do so by creating a new issue in the relevant repositories of @browser-fs
