### ISSUE TITLE
Question: Storing into ZipFS and using Buffer to create Blobs 

### ISSUE THREAD

**Issue by puppeteer701vungle** [jvilk/BrowserFS#275]
Hi Guys, 

I am new to BrowserFS, I have a question, it is probably a stupid one. Some context, I am building a previewer which will download a zip bundle and inside the zip it has all the content of the page. The idea that I have is, not to store the ZIPS and extract them on server, and then put the SRC of the iframe to that location, but to somehow use users/browsers storage to present the page in iframe. I see that browserfs allows me to save the zip files into ZipFS, and here is where the question lies, does browserfs save the file in the memory of the server(where previewer is running) or does it use clients/browsers devices memory?

**Comment by dr-vortex** [comment]
@puppeteer701vungle BrowserFS uses the browser's memory (which is client side)

**Comment by dr-vortex** [comment]
Closing this question since it is stale.
