### ISSUE TITLE
OnWrite events

### ISSUE THREAD

**Issue by hypernova7** [jvilk/BrowserFS#279]
It would be great if in the "writeFile" HTML5FS function they added the progress function to create a progress bar, something like this:

```javascript
var progress = function progress(writer) {
    console.log((writer.loaded/writer.total)*100);
};
var err = function err(e) {
    console.log(e);
}
fs.writeFile(filename, data, progress, err);
```

**Comment by dr-vortex** [comment]
Closing (stale). If you would like to reopen this issue, please do so by creating a new issue in the relevant repositories of @browser-fs
