### ISSUE TITLE
Intent to support the new Chrome Filesystem API?

### ISSUE THREAD

**Issue by benjamingr** [jvilk/BrowserFS#282]
Hey are there any plans to support the new experimental Filesystem API? https://github.com/WICG/native-file-system

**Comment by oeway** [comment]
+1 Now it has been renamed to File System Access API and enabled by default since Chrome 86.
Just tried it and works nicely by following this tutorial https://web.dev/file-system-access/

**Comment by DustinBrett** [comment]
I also had a desire for the File System Access API and I've finally taken the time to write the backend. The PR is here if you want to try it out.

https://github.com/jvilk/BrowserFS/pull/321

**Comment by hello-smile6** [comment]
@DustinBrett Could you publish your version to the NPM registry?

**Comment by DustinBrett** [comment]
Hoping #321 can at some point get traction. Added a new comment based on another request for this to be on npm. I'm not much for publishing to npm, but if someone wanted to fork this repo if it is indeed unmaintained, perhaps that could become the place for new PR's from anyone who wants to continue BrowserFS's evolution.

**Comment by dr-vortex** [comment]
Marking this as completed since #321 was merged.
