### ISSUE TITLE
Dropbox API v1 Retired

### ISSUE THREAD

**Issue by thewildman** [jvilk/BrowserFS#283]
Hi, as per documentation I've been using version 0.10.3 of the dropbox library to create the client, but then a simple fs.writefile fails and the result of the XHR query is {"error": "v1_retired"}.

I gave the latest SDK a try, but then my script simply fail when creating the DropboxFS.

Is there something obvious I'm missing here ?

**Comment by dr-vortex** [comment]
@thewildman Does this bug still exist?

**Comment by thewildman** [comment]
Sorry I have no idea, I've not been using it for a long time.

**Comment by dr-vortex** [comment]
Fixed. See #144
