### ISSUE TITLE
Unexpected Error in writing File

### ISSUE THREAD

**Issue by elliott-wen** [jvilk/BrowserFS#286]
Hi, there. 

When I tried to execute the following simple script, it just threw an error.

```
<script type="text/javascript" src="browserfs.js"></script>
<script type="text/javascript">
  BrowserFS.install(window);
  // Configures BrowserFS to use the LocalStorage file system.
  BrowserFS.configure({
    fs: "LocalStorage"
  }, function(e) {
    if (e) {
      // An error happened!
      throw e;
    } else {
        console.log("Hello world");
        var fs = BrowserFS.BFSRequire('fs');
        var datain = new ArrayBuffer(32);
        fs.writeFile("test.txt", datain, function(e, data){
          console.log(e);
          console.log(data);
         });
    }
  });
</script>
```

TypeError: e.copy is not a function
    at e.n.writeSync (browserfs.rollup.js:3339)
    at e.n.write (browserfs.rollup.js:3282)
    at browserfs.rollup.js:2853
    at e.open (browserfs.rollup.js:2975)
    at et.writeFile (browserfs.rollup.js:2837)
    at x.writeFile (browserfs.rollup.js:951)
    at Object.D.<computed>.A.<computed> [as writeFile] (browserfs.rollup.js:1787)
    at index.html:32
    at passthrough.js:1
    at Function.e.Create (passthrough.js:1)

Could you kindly enlighten me what's going on? Have tried 1.4.3. and 2.0. 

Only happened when writting typearrays or arraybuffer, works fine for string

**Comment by elliott-wen** [comment]
It turns out it is not a bug, I needed to wrap the typearray with buffer.from, but I just wonder whether it makes sense to automate this step, since strings are already auto wrapped.

**Comment by jvilk** [comment]
BrowserFS emulates the Node API, so I thought that it should be clear that you need to use `Buffer`, not `ArrayBuffer`. I don't believe the Node API accepts bare `ArrayBuffer`s (does it?). It accepts strings for legacy reasons.

As a result, I am marking this as WONTFIX.
