### ISSUE TITLE
plase add a htmlfs example thx!

### ISSUE THREAD

**Issue by dirkhe1051931999** [jvilk/BrowserFS#290]
i not find a htmlfs example for `HTML5FS`
i according to my understanding coding such as

```ts
BrowserFS.configure(
  {
    fs: 'HTML5FS',
  },
  function(e: Error) {
    if (e) {
      // An error happened!
      throw e;
    }
  },
);
```
has a error  `Cannot read property 'size' of undefined`

help!!!

**Comment by dr-vortex** [comment]
Closing since #357
