### ISSUE TITLE
Support for for cordova-plugin-file would nice

### ISSUE THREAD

**Issue by bessw** [jvilk/BrowserFS#293]
[cordova-plugin-file](https://github.com/apache/cordova-plugin-file) gives access to the filesystem on Android, iOS, OSX and Windows UWP platforms.

Together with support for node fs like in #184 and Electron we would have a unified filesystem api across all relevant platforms (even including browser), this would make writing cross platform apps much easier.

**Comment by dr-vortex** [comment]
Closing (stale). If you would like to reopen this issue, please do so by creating a new issue in the relevant repositories of @browser-fs
