### ISSUE TITLE
Question: What's the easiest way to interact with a remote disk?

### ISSUE THREAD

**Issue by jay-khatri** [jvilk/BrowserFS#295]
Hi there. I just came across this library, and am having trouble understanding exactly what it does.

I'd like to prototype something that allows someone to create/edit files on a remote disk from the browser. What's the easiest way to setup something like this given the list of `Backends` in the readme? 

Also, my apologies if this isn't the correct place to be posting this.

**Comment by dr-vortex** [comment]
Closing as stale
