### ISSUE TITLE
Implementing http sync backend

### ISSUE THREAD

**Issue by NexusNull** [jvilk/BrowserFS#305]
I'm am looking for a backend that essentially allows a user to create file on a remote filesystem.
I already worked myself through the code so I'm about ready to implement such a thing.
My question is, would this be an appreciated contribution to this repo, and if so are there any guidelines you want me to follow?
It seems other people are looking for the exact thing I'm trying to build e.g. #295 

Alright let's get into the details,
I was thinking of using express as a webserver to server to serve the filesystem.

/fs/* as default route for all files with the following methods 
post: creating file
get: reading file
delete: deleting file

/fsIndex/* to retrieve stat information about a file or folder

For the backend I'd like repurpose HTTPRequest as most things will be identical except for the ability of being able to write files.

In any case I'd love to hear suggestions or feedback of any kind.

**Comment by lahwran** [comment]
Did you end up doing this? I'm toying with just such an idea myself.

**Comment by NexusNull** [comment]
Yes, I switched gears tough.
I thought using an already existing technology rather than inventing one would be better for the long term.
I am now using WebDav as a backend so I don't have to create something myself.
https://github.com/NexusNull/BrowserFS my version also passes all the tests

**Comment by lahwran** [comment]
Awesome! I'll look into your code when I'm playing with this next.
