### ISSUE TITLE
Integration with the Emscripten file system in a webworker

### ISSUE THREAD

**Issue by oeway** [jvilk/BrowserFS#310]
Hi, I am trying to integrate the emscripten file system work with BrowserFS in a webworker. Here is the setup I want to achieve:
1. in the main thread, mount a indexeddb file system with browserfs
2. in the worker thread I would like to attach to the file system in the main thread, create an emscripten interface for browserfs and mount it to a WASM library.

As I understand from a comment [here](https://github.com/jvilk/BrowserFS/issues/89#issuecomment-71087664), I would also need the AsyncMirror to make an sync interface for the emscripten interface.

This is what I have tried but **failed** to get it work:

Main thread
```js
  // Listen for remote file system requests.
  BrowserFS.FileSystem.WorkerFS.attachRemoteListener(webWorkerObject);

```

WebWorker
```js

BrowserFS.configure({
  fs: "AsyncMirror",
  options: {
    sync: { fs: "InMemory" },
    async: {  fs: "WorkerFS", options: { worker: self } }
  }
}, function(e) {
  if (e) {
    // An error happened!
    throw e;
  }
  let FS = my_wasm_module.FS;
  let PATH = my_wasm_module.PATH;
  // Create an Emscripten interface for the BrowserFS
  const BFS = new BrowserFS.EmscriptenFS(FS, PATH);
  // Create mount point in Emscripten FS
  FS.createFolder(FS.root, 'data', true, true);
  // Mount BrowserFS into Emscripten FS
  FS.mount(BFS, {root: '/'}, '/data');
});

```
Is this the way to use it?

**Comment by cloudwalkerfre** [comment]
@oeway Hey, are you trying to bind it with pyodide? Was doing the same thing here, hope you find a solution, running pyodide in main thread is causing my App render to suffer, I guess this is the only way to do it.

**Comment by oeway** [comment]
Yes, I am trying to use it with Pyodide, however I haven't figure it out yet.

**Comment by cloudwalkerfre** [comment]
I was able to do just the normal WorkerFS.Create, then have the cb fs as global, call it in pyodide like
```
import js
import pandas as pd

js.fs.mkdir('test')
```
I can see the newly created folder in mainthread, I guess we can take a detour, something like `pd.read_csv(StringIO(js.fs.readFile))`, but that's not pretty

**Comment by leviathan747** [comment]
I was able to get it working with the following in the web worker:

```
15   // set up file system
 16   await new Promise((resolve, reject) => {
 17     BrowserFS.configure({
 18       fs: 'AsyncMirror',
 19       options: {
 20         sync: { fs: 'InMemory' },       
 21         async: { fs: 'WorkerFS', options: { worker: self } }
 22       }
 23     }, function(e) {
 24       if (e) { reject(e); }
 25       resolve();
 26     });
 27   });
 28   const BFS = new BrowserFS.EmscriptenFS(Module.FS, Module.PATH, Module.ERRNO_CODES);
 29   Module.FS.mkdir('/data');
 30   Module.FS.mount(BFS, {root: '/'}, '/data');
```

I used your code as a base, but the part with `ERRNO_CODES` ended up being key for me -- I was getting errors anytime I tried to `stat` a file.
