### ISSUE TITLE
Browserfs is brocken.

### ISSUE THREAD

**Issue by sahilrajput03** [jvilk/BrowserFS#314]
https://github.com/sahilrajput03/browser-fs-test

Why is it simply not working..?

![image](https://user-images.githubusercontent.com/31458531/115984928-15ef2080-a5c7-11eb-826a-6997656627c8.png)

**Comment by jcubic** [comment]
First thing you need to check what exactly you have in your browserfs.min.js to be sure that you have correct file you can grab browserFS from cdn like https://www.jsdelivr.com/

Another thing is that you have NodeJS code inside js.js this will not work, you can use require inside browser.
