### ISSUE TITLE
How to access files from Browser within BrowserFS?

### ISSUE THREAD

**Issue by astuy** [jvilk/BrowserFS#316]
Within my Browser Javascript code I want to load a zip file (with relatively linked files) from a server, extract it inside browser and pass the entry file over to another library.

BrowserFS looks very promising and I understand, how to initialize BrowserFS. But what would be the address of a file inside the zip, which I would pass to the other library and from which it resolves the other files?

Or is this not possible with BrowserFS?

**Comment by dr-vortex** [comment]
@astuy Have you resolved this issue yet?

If not, you can mount the zip file using `ZipFS` and read files by their path.

**Comment by dr-vortex** [comment]
Closing as stale
