### ISSUE TITLE
Is there a missing dependency on `ERRNO_CODES` from emscripten?

### ISSUE THREAD

**Issue by sbc100** [jvilk/BrowserFS#319]
See https://github.com/emscripten-core/emscripten/issues/14783

I'm not familiar with how BrowserFS is used but in order to use emscripten's `$ERRNO_CODES` it somehow needs to be pulled in as a dependency (for library JS files this involves a __deps entry, otherwise we have the `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` command line setting).

My understanding is that prior to https://github.com/emscripten-core/emscripten/pull/14730, `$ERRNO_CODES` was likely being pulled in indirectly.

**Comment by dr-vortex** [comment]
@sbc100 BrowserFS does not use Emscripten's error codes (see [api_error.ts](https://github.com/jvilk/BrowserFS/blob/master/src/core/api_error.ts))
