### ISSUE TITLE
No apparent way to determine mime type of a file

### ISSUE THREAD

**Issue by TheAwesome98-Real** [jvilk/BrowserFS#324]
When using node, to determine the type of a file, the `file-type` or `mime` packages might be used. But when using BrowserFS, these packages aren't available.
```js
// even if you try (lol)
Uncaught TypeError: n is null
    require browserfs.ts:31
    <anonymous> debugger eval code:1
```
How can I find out the mime-type of a file using BrowserFS?

**Comment by dr-vortex** [comment]
@TheAwesome98-Real You may want to look into non-node libraries similar to `file-type` or `mime`.
