### ISSUE TITLE
The Future of This Project

### ISSUE THREAD

**Issue by chuanqisun** [jvilk/BrowserFS#328]
Hi, 

This repo seems to be inactive. Could you share some info just to help set the expectation?

- What is the current project status, e.g.: archive, or fix-only?
- Any alternative projects to recommend?

Thank you!

**Comment by jinseok9338** [comment]
Yeah that's the vibe I got this from this project. But in when you think about it, you rather want to use actual storage solution rather than storage in the browser

**Comment by jinseok9338** [comment]
https://cloud.google.com/storage/docs/gcs-fuse
something like this

**Comment by chuanqisun** [comment]
Thank you @jinseok9338.

I was looking for a Browser-only Filesystems to build distributed apps that don't rely on a server. Maybe Filesystem is too low level. Indexed DB or sql.js might be better alternatives.

 (and I love Snoopy too)

**Comment by dr-vortex** [comment]
@chuanqisun and @jinseok9338,

I've recently become a maintainer for the project. 

> This repo seems to be inactive. Could you share some info just to help set the expectation?
>
> - What is the current project status, e.g.: archive, or fix-only?
> - Any alternative projects to recommend?

I'm hoping to work on some enhancements in the mid-term future but for now I'm focusing on fixing any major bugs and updating the CI/CD setup.
