### ISSUE TITLE
Addition of SessionStorage backend

### ISSUE THREAD

**Issue by ragusrinivasan** [jvilk/BrowserFS#330]
Can session storage be added to browserfs?

**Comment by dr-vortex** [comment]
@ragusrinivasan Since session storage and local storage both use [`Storage`](https://developer.mozilla.org/Web/API/Storage) it should be fairly easy to implement.

**Comment by dr-vortex** [comment]
Added in d922c74. Use it like so:

```ts
import { configure, fs } from 'browserfs';
await configure({ '/example/session': { fs: 'Storage', options: { storage: sessionStorage } } })
```
