### ISSUE TITLE
Using MountableFileSystem with a backend other than `InMemory`

### ISSUE THREAD

**Issue by Froggo8311** [jvilk/BrowserFS#337]
In the MountableFileSystem documentation, it describes how it acts as a standard `InMemory` filesystem. Is there any way I could use it instead with `IndexedDB`?

**Comment by DustinBrett** [comment]
I have an example of this working on my project if you're interested.

https://github.com/DustinBrett/daedalOS/blob/main/contexts/fileSystem/FileSystemConfig.ts

```js
{
  fs: "MountableFileSystem",
  options: {
    "/": {
      fs: "OverlayFS",
      options: {
        readable: {
          fs: "HTTPRequest",
          options: { index },
        },
        writable: {
          fs: writeToMemory ? "InMemory" : "IndexedDB",
        },
      },
    },
  },
}
```

**Comment by dr-vortex** [comment]
You can simply mount an overlayFS (overlaying an IndexedDB FS) to "/".

**Comment by DustinBrett** [comment]
That's true you may not even need `MountableFileSystem` depending on your use case. For me I use it because I mount other FS's after load such as IsoFS or ZipFS.

**Comment by dr-vortex** [comment]
@Froggo8311 Has your question been answered?
