### ISSUE TITLE
New project ownership?

### ISSUE THREAD

**Issue by dr-vortex** [jvilk/BrowserFS#339]
@emeryberger,

I've seen you merging some PRs recently and was wondering what your position is with the project? I love the new activity!

**Comment by emeryberger** [comment]
@jvilk was my PhD student at UMass Amherst in the PLASMA lab (https://github.com/plasma-umass). This project was part of joint work (Doppio - https://plasma-umass.org/doppio-demo/, and Browsix - https://browsix.org/). Right now, John doesn't have the cycles to devote to maintaining the project, so I'm helping out!
