### ISSUE TITLE
Triage permissions?

### ISSUE THREAD

**Issue by dr-vortex** [jvilk/BrowserFS#340]
@emeryberger As I'd like to work on BrowserFS a lot (and contribute more significant changes), could I have triage permissions on the repository?

**Comment by emeryberger** [comment]
I appreciate the offer. Drop me a mail (emery.berger@gmail.com) and let's have a chat!

**Comment by emeryberger** [comment]
@jvilk should be adding you soon!

**Comment by dr-vortex** [comment]
@emeryberger I saw, Thanks!
