### ISSUE TITLE
Link to new repositories?

### ISSUE THREAD

**Issue by kkoreilly** [jvilk/BrowserFS#376]
It seems like development of BrowserFS has moved to https://github.com/browser-fs and its repositories (like https://github.com/browser-fs/core). Is there any reason this is not mentioned in the README?

**Comment by dr-vortex** [comment]
Yes, I am waiting until all of the codebase is moved over, available on NPM, and stable. Some of the backends (e.g. Zip and Iso) have not been.

**Comment by jcubic** [comment]
The README shows wrong link. It point to `BrowserFS` which is some PHP org, and not `browser-fs`.

**Comment by dr-vortex** [comment]
@jcubic Thank you for catching that. I've updated the link.
