### ISSUE TITLE
readdirSync throws an error if the path ends with a separator

### ISSUE THREAD

**Issue by OguzhanUmutlu** [jvilk/BrowserFS#378]
This works fine:
```js
fs.readdirSync(".")
```

This throws a "Maximum call stack size exceeded" error:
```js
bfs.readdirSync("./")
```

I'm using it on web, with LocalStorage option

**Comment by james-pre** [comment]
Hi @OguzhanUmutlu, this project is not being maintained. Please read [README.md](https://github.com/jvilk/BrowserFS/blob/master/README.md) for more details. I am actively maintaining a fork called [ZenFS](https://github.com/zen-fs/core).

**Comment by OguzhanUmutlu** [comment]
Alright.
