### ISSUE TITLE
Make cloud storage accounts under an organisation name

### ISSUE THREAD

**Issue by lavelle** [jvilk/BrowserFS#45]
Currently the Dropbox and Google Drive apps are registered under my accounts. We should create accounts with these services with some BrowserFS email address, so that we can all log in and access the app consoles, generate new API keys etc.

Any feedback users have would then go to the shared email account too, which is better than it going to my personal account.

**Comment by jvilk** [comment]
I don't see the need for this now, as the credentials are only used during testing.
