### ISSUE TITLE
Make a BrowserFS GitHub organisation and migrate the repos to it

### ISSUE THREAD

**Issue by lavelle** [jvilk/BrowserFS#46]
I think we've agreed on keeping things modular and having separate repos for each backend (or each one not currently this repo, at least). To make it easier for users to find all the backends, it would be good to put them all under one account.

This account would have:
- This core repo
- The cloud backends
  - Dropbox
  - Google Drive
- The local backends, if we extract them from this repo
- The test suite, if we extract it from this repo (IMO a good idea, because otherwise the only way to test is to import the backends into the core repo, which is the wrong way round)
- The website/homepage if we make one
## Currently

`[Core + Test suite] <- [Backends]`
## Proposed

`[Test suite] <- [Backends] <- [Core]`

**Comment by jvilk** [comment]
Someone has claimed the browserfs GitHub organization. I don't know who, as nothing about it is public. :frowning:

**Comment by jvilk** [comment]
The owners of the browserfs GitHub organization are using it privately and do not wish to rename, so I'll have to find a new name to use.

**Comment by jvilk** [comment]
Due to lack of interest from others, I am closing this issue. I do not believe a whole organization with many tiny modules is worth the effort, given that I am the only maintainer. I would rather support making it easier to build customized builds.
