### ISSUE TITLE
CachedFileSystem

### ISSUE THREAD

**Issue by jvilk** [jvilk/BrowserFS#95]
A _CachedFileSystem_ wraps a _cache file system_ and a _backing file system_, and caches the backing file system's content into the cache file system according to a customizable policy.

If the _cache file system_ persists across page loads, its contents will be reused according to the specified policy.

The file system will be greatly useful for file systems that are backed by network storage (e.g. `XMLHttpRequest` and `Dropbox`) and by compressed files (e.g. `ZipFS`). It will also allow us to remove custom inflexible caching solutions currently deployed in e.g. the `XMLHttpRequest` file system.

**Comment by dr-vortex** [comment]
Closing since the proposal is being tracked in #191.
