### ISSUE TITLE
path.dirname('a/b') bug

### ISSUE THREAD

**Issue by Narazaka** [jvilk/BrowserFS#96]
path.dirname (node.js like) bug

path.dirname('a/b') returns not 'a' but '.'

fix code:
dist/browserfs.js line 3692
> if (sections.length > 1) {
to
> if (sections.length >= 1) {

**Comment by Narazaka** [comment]
sorry fix code is wrong

**Comment by jvilk** [comment]
Thanks for the bug report! I'm fixing now.

**Comment by jvilk** [comment]
Thanks for reporting this bug!
